name: VShop
main: com.velozity.vshop.Main
version: 1.0
author: Velozity
api-version: 1.15

commands:
  vshop:
    description: Commands for VShop
    aliases: vs

permissions:
  vshop.editmode.admin:
    description: All permissions to setup an admin sign shop
    children:
      vshop.createshop: true
      vshop.editgui: true
