name: VShop
main: com.velozity.vshop.Main
version: 1.0
author: Velozity
api-version: 1.15

softdepend: [Vault, PlaceholderAPI]

commands:
  vshop:
    description: Commands for VShop
    aliases: vs

permissions:
  vshop.admin:
    description: All permissions to setup an admin sign shop
    children:
      vshop.createshop: true
      vshop.destroyshop: true
      vshop.editormode: true
      vshop.stats: true
  vshop.mod:
    description: Permissions to manage sign shops (not create or destroy)
    children:
      vshop.createshop: false
      vshop.destroyshop: false
      vshop.editormode: true
      vshop.stats: true
